version: "3.8"

services:
  nats: 
    image: nats:latest
    command: "-js -c /etc/nats/nats.conf"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf   
    expose:
      - '4222'
    ports:
      - 4222:4222
      - 8222:8222
      - 9222:9222
    hostname: nats
    
  service:
    image: alephp/moleculerjs:latest
    container_name: moleculerjs
    env_file: docker-compose.env
    volumes:
      - ./:/home/node/app
    environment:
      SERVICE: sample
      NODE_ENV: production

    ports:
      - 8080:8080
      - 3000:3000
    